apiVersion: v1
kind: ConfigMap
metadata:
  name: vibectl-server-config
  labels:
    app: vibectl-server
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 50051
      default_model: "anthropic/claude-3-7-sonnet-latest"
      max_workers: 10
      log_level: "INFO"

    tls:
      enabled: true
      cert_file: "/ca-data/server_certs/localhost/localhost.crt"
      key_file: "/ca-data/server_certs/localhost/localhost.key"

    # Enable HTTP Strict Transport Security (applies to gRPC metadata)
    hsts:
      enabled: true            # Emit Strict-Transport-Security header
      max_age: 31536000        # 1 year in seconds
      include_subdomains: false  # No sub-domain protection needed for demo
      preload: false           # Do not request preload list inclusion for demo

    # ACME disabled (using CA mode instead)
    acme:
      enabled: false

    jwt:
      enabled: true
      secret_key: null
      secret_key_file: "/etc/vibectl/secret/jwt-secret"
      algorithm: "HS256"
      issuer: "vibectl-server"
      expiration_days: 30
