apiVersion: v1
kind: Secret
metadata:
  name: vibectl-server-jwt
  labels:
    app: vibectl-server
type: Opaque
data:
  jwt-secret: ZGVtby1zZWNyZXQtZm9yLXZpYmVjdGwtc2VydmVyLWp3dC1zaWduaW5nLWtleQ==
  # Base64 encoded: "demo-secret-for-vibectl-server-jwt-signing-key"
