apiVersion: v1
kind: Service
metadata:
  name: vibectl-server
  labels:
    app: vibectl-server
    mode: acme-http
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9095"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
  - name: grpc-tls
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: http-acme
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9095
    targetPort: 9095
  selector:
    app: vibectl-server
---
# LoadBalancer service for external access (HTTP-01 requires both HTTP and HTTPS)
apiVersion: v1
kind: Service
metadata:
  name: vibectl-server-external
  labels:
    app: vibectl-server
    mode: acme-http
  annotations:
    metallb.universe.tf/address-pool: vibectl-demo-pool
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: vibectl-server
