apiVersion: v1
kind: Service
metadata:
  name: vibectl-server
  labels:
    app: vibectl-server
    mode: acme
spec:
  type: ClusterIP
  ports:
  - name: grpc-tls
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: vibectl-server
---
# NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: vibectl-server-external
  labels:
    app: vibectl-server
    mode: acme
  annotations:
    metallb.universe.tf/address-pool: vibectl-demo-pool
spec:
  type: LoadBalancer
  ports:
  - name: grpc-tls
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: vibectl-server
---
# Additional service for external access with LoadBalancer (optional)
# Uncomment this if you want to test with a real LoadBalancer
# apiVersion: v1
# kind: Service
# metadata:
#   name: vibectl-server-lb
#   labels:
#     app: vibectl-server
#     mode: acme
# spec:
#   type: LoadBalancer
#   ports:
#   - name: grpc-tls
#     port: 443
#     targetPort: 443
#     protocol: TCP
#   selector:
#     app: vibectl-server 