apiVersion: v1
kind: Service
metadata:
  name: vibectl-server
  labels:
    app: vibectl-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9095"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: 30551
    name: grpc
  - port: 9095
    targetPort: 9095
    nodePort: 30995
    name: metrics
  selector:
    app: vibectl-server
---
# Service to expose the JWT token data volume for demo script access
apiVersion: v1
kind: Service
metadata:
  name: vibectl-server-demo
  labels:
    app: vibectl-server
    component: demo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: demo-http
  selector:
    app: vibectl-server
