apiVersion: v1
kind: Service
metadata:
  name: vibectl-server
  labels:
    app: vibectl-server
    mode: acme
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9095"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
  - name: grpc-tls
    port: 443
    targetPort: 443
    protocol: TCP
  - name: metrics
    port: 9095
    targetPort: 9095
  selector:
    app: vibectl-server
---
# NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: vibectl-server-external
  labels:
    app: vibectl-server
    mode: acme
  annotations:
    metallb.universe.tf/address-pool: vibectl-demo-pool
spec:
  type: LoadBalancer
  ports:
  - name: grpc-tls
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: vibectl-server
