repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # Temporarily disable the standard check-yaml hook that doesn't support multi-document YAML
      # - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # Add a custom hook for YAML validation that supports multi-document YAML
  - repo: local
    hooks:
      - id: custom-check-yaml
        name: custom YAML validator
        description: Validates YAML files including multi-document YAMLs
        entry: python -c 'import sys, yaml; [yaml.safe_load_all(open(f)) for f in sys.argv[1:]]'
        language: system
        files: \.(ya?ml)$
        types: [file, yaml]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
        # Exclude generated protobuf/gRPC code from linting
        exclude: |
          (?x)^(
              vibectl/proto/llm_proxy_pb2\.py|
              vibectl/proto/llm_proxy_pb2_grpc\.py
          )$
      - id: ruff-format
        # Exclude generated protobuf/gRPC code from formatting
        exclude: |
          (?x)^(
              vibectl/proto/llm_proxy_pb2\.py|
              vibectl/proto/llm_proxy_pb2_grpc\.py
          )$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        pass_filenames: false
        args: [vibectl, tests]
        additional_dependencies:
          - pydantic
          - types-PyYAML
          - types-setuptools
          - grpc-stubs
          - types-protobuf
          - pytest
          - types-click
          - asyncclick
          - pytest-mock
          # Add other specific type stubs as needed for your project

# Re-add the local pytest hook
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
