repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # Temporarily disable the standard check-yaml hook that doesn't support multi-document YAML
      # - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # Add a custom hook for YAML validation that supports multi-document YAML
  - repo: local
    hooks:
      - id: custom-check-yaml
        name: custom YAML validator
        description: Validates YAML files including multi-document YAMLs
        entry: python -c 'import sys, yaml; [yaml.safe_load_all(open(f)) for f in sys.argv[1:]]'
        language: system
        files: \.(ya?ml)$
        types: [file, yaml]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-PyYAML
          - types-setuptools
          # Add other specific type stubs as needed for your project

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
