apiVersion: v1
kind: ConfigMap
metadata:
  name: diff-demo-cm
  namespace: diff-demo-ns
data:
  key1: value1
  key2: "initial data"
---
apiVersion: v1
kind: Secret
metadata:
  name: diff-demo-secret
  namespace: diff-demo-ns
type: Opaque
data:
  username: dXNlcjE= # user1
  password: cGFzc3dvcmQxMjM= # password123
