services:
  services:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID:-999}
    container_name: chaos-monkey-services
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - VIBECTL_ANTHROPIC_API_KEY=${VIBECTL_ANTHROPIC_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VIBECTL_MODEL=${VIBECTL_MODEL:-claude-3.7-sonnet}
      - SESSION_DURATION=${SESSION_DURATION:-30}
      - VERBOSE=${VERBOSE:-false}
      - NODE_PORT_1=${NODE_PORT_1:-30001}
      - NODE_PORT_2=${NODE_PORT_2:-30002}
      - NODE_PORT_3=${NODE_PORT_3:-30003}
      - KIND_CONTAINER=chaos-monkey-control-plane
    healthcheck:
      test: ["CMD", "bash", "-c", "kubectl get nodes 2>/dev/null | grep -q Ready"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - chaos-monkey-network

  blue-agent:
    build:
      context: .
      dockerfile: ./blue-agent/Dockerfile
    container_name: chaos-monkey-blue-agent
    depends_on:
      services:
        condition: service_healthy
    environment:
      - VIBECTL_ANTHROPIC_API_KEY=${VIBECTL_ANTHROPIC_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VIBECTL_MODEL=${VIBECTL_MODEL:-claude-3.7-sonnet}
      - SESSION_DURATION=${SESSION_DURATION:-30}
      - MEMORY_MAX_CHARS=${BLUE_MEMORY_MAX_CHARS:-2000}
      - ACTION_PAUSE_TIME=${BLUE_ACTION_PAUSE_TIME:-30}
      - VERBOSE=${VERBOSE:-false}
      - NODE_PORT_1=${NODE_PORT_1:-30001}
      - NODE_PORT_2=${NODE_PORT_2:-30002}
      - NODE_PORT_3=${NODE_PORT_3:-30003}
    networks:
      - chaos-monkey-network

  red-agent:
    build:
      context: .
      dockerfile: ./red-agent/Dockerfile
    container_name: chaos-monkey-red-agent
    depends_on:
      services:
        condition: service_healthy
    environment:
      - VIBECTL_ANTHROPIC_API_KEY=${VIBECTL_ANTHROPIC_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VIBECTL_MODEL=${VIBECTL_MODEL:-claude-3.7-sonnet}
      - SESSION_DURATION=${SESSION_DURATION:-30}
      - MEMORY_MAX_CHARS=${RED_MEMORY_MAX_CHARS:-2000}
      - ACTION_PAUSE_TIME=${RED_ACTION_PAUSE_TIME:-45}
      - VERBOSE=${VERBOSE:-false}
      - NODE_PORT_1=${NODE_PORT_1:-30001}
      - NODE_PORT_2=${NODE_PORT_2:-30002}
      - NODE_PORT_3=${NODE_PORT_3:-30003}
    networks:
      - chaos-monkey-network

  # Commented out non-essential services for initial development/debugging
  # poller:
  #   build:
  #     context: ./poller
  #     dockerfile: Dockerfile
  #   container_name: chaos-monkey-poller
  #   depends_on:
  #     services:
  #       condition: service_healthy
  #   environment:
  #     - SESSION_DURATION=${SESSION_DURATION:-30}
  #     - POLLER_INTERVAL=${POLLER_INTERVAL:-5}
  #     - POLLER_RETRY_POLICY=${POLLER_RETRY_POLICY:-standard}
  #     - VERBOSE=${VERBOSE:-false}
  #   networks:
  #     - chaos-monkey-network

  # overseer:
  #   build:
  #     context: ./overseer
  #     dockerfile: Dockerfile
  #   container_name: chaos-monkey-overseer
  #   depends_on:
  #     services:
  #       condition: service_healthy
  #   environment:
  #     - SESSION_DURATION=${SESSION_DURATION:-30}
  #     - METRICS_INTERVAL=${METRICS_INTERVAL:-15}
  #     - VISUALIZATION=${VISUALIZATION:-true}
  #     - VERBOSE=${VERBOSE:-false}
  #   networks:
  #     - chaos-monkey-network
  #   ports:
  #     - "8080:8080" # Dashboard UI

networks:
  chaos-monkey-network:
    driver: bridge
