kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: chaos-monkey
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.245.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # Bind to all interfaces within the container
        bind-address: "0.0.0.0"
