apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-access-to-system-monitoring
  namespace: system-monitoring
spec:
  # Block all ingress traffic except from specific pods
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  # Allow only traffic from system namespace resources like kube-system
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    # Allow traffic from the monitoring namespace
    - namespaceSelector:
        matchLabels:
          purpose: system
  # Allow DNS
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
