apiVersion: v1
kind: ConfigMap
metadata:
  name: vibectl-server-config
  labels:
    app: vibectl-server
data:
  config.yaml: |
    server:
      host: 0.0.0.0
      port: 50051
      require_auth: true
      use_tls: false
    jwt:
      secret_key_file: /etc/vibectl/secret/jwt-secret
      issuer: demo-proxy
      expiration_days: 30
