apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibectl-server
  labels:
    app: vibectl-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibectl-server
  template:
    metadata:
      labels:
        app: vibectl-server
    spec:
      containers:
      - name: vibectl-server
        image: ghcr.io/vibectl/vibectl-server:latest
        args: ["serve", "--config", "/etc/vibectl/config/config.yaml"]
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: config
          mountPath: /etc/vibectl/config
        - name: jwt-secret
          mountPath: /etc/vibectl/secret
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: vibectl-server-config
      - name: jwt-secret
        secret:
          secretName: vibectl-server-secret
