apiVersion: v1
kind: Service
metadata:
  name: vibectl-server
  labels:
    app: vibectl-server
spec:
  type: NodePort
  selector:
    app: vibectl-server
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    nodePort: 30551
