apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-services-config
  namespace: services
data:
  config.json: |
    {
      "environment": "demo",
      "version": "0.1.0",
      "config": {
        "logLevel": "info",
        "responseTimeout": 5,
        "maxRetries": 3
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-content
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: frontend-content
        configMap:
          name: frontend-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-content
  namespace: services
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Chaos Monkey Demo</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px;
          text-align: center;
        }
        h1 {
          color: #333;
        }
        .status {
          padding: 20px;
          background-color: #f1f1f1;
          border-radius: 5px;
          margin: 20px 0;
        }
      </style>
    </head>
    <body>
      <h1>Service Status: Online</h1>
      <div class="status">
        <p>This service is currently operational.</p>
        <p>Service ID: frontend-v1</p>
        <p>Last updated: <span id="timestamp"></span></p>
      </div>
      <script>
        document.getElementById('timestamp').innerText = new Date().toISOString();
        setInterval(function() {
          document.getElementById('timestamp').innerText = new Date().toISOString();
        }, 1000);
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: services
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: ${NODE_PORT_1}
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: backend-content
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: backend-content
        configMap:
          name: backend-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-content
  namespace: services
data:
  index.html: |
    {
      "status": "ok",
      "service": "backend-api",
      "version": "1.0",
      "time": "dynamic",
      "endpoints": [
        "/api/users",
        "/api/products",
        "/api/orders"
      ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: services
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80
    nodePort: ${NODE_PORT_2}
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: api-content
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: api-content
        configMap:
          name: api-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-content
  namespace: services
data:
  index.html: |
    {
      "status": "healthy",
      "service": "api-service",
      "version": "0.1.0",
      "endpoints": ["/api/v1/status", "/api/v1/users", "/api/v1/data"]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: services
spec:
  selector:
    app: api-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: ${NODE_PORT_3}
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: services
spec:
  selector:
    app: database
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: services
spec:
  selector:
    app: cache-service
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP 